# authendication credintials
credentials:
  usernames:
    ahtesham:
      email: kalim@gmail.com
      name: ahtesham uddowla
      password: $2b$12$0Q6x6DBU6oSYr1TE.db.oOJuDDiOMVve6DJ6l6r2DXD68oRxSJ4DW # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - kalim@growwithdata.net



db:
  host: "localhost"
  user: "root"
  passwd: "root"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "kalim.resource@gmail.com"
  pass: '@&&@+7'